name: CI-Test

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        working-directory: PasswordEncryption
        run: |
            python3 -m pip install Appium-Python-Client
            python3 test_appium.py

