name: CI-Test

on: [push]

env:
  DAY_OF_WEEK: Monday
  
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          echo "DAY_OF_WEEK=Sunday" >> $GITHUB_ENV
          echo "$DAY_OF_WEEK!"
