name: CI-Test

on: [push]

env:
  DAY_OF_WEEK: Monday
  SCHEME: SmokeTest
  PROJECT_NAME: DemoTest

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['14.5','15.2']
          devices: ['iPhone 12 Pro Simulator','iPhone 11 Pro Simulator']
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        with:
          ref: cicd_testing
      - name: building
        run: |
          xcodebuild -workspace PasswordEncryption.xcworkspace -scheme PasswordEncryption -configuration Debug -destination "platform=iOS Simulator,OS=15.2,name=iPod touch (7th generation)" -derivedDataPath SmokeBuild
          cd ~/work/$PROJECT_NAME/$PROJECT_NAME/SmokeBuild/
          ls
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        working-directory: PasswordEncryption
        run: |
            echo '${{matrix.destiation }}'
            python3 -m pip install Appium-Python-Client
            python3 test_appium.py ${{ matrix.destination }} "${{ matrix.devices }}"

