name: CI-Test

on: [push]

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['14.5','15.2']
          devices: ['iPhone 12 Pro Simulator','iPhone 11 Pro Simulator']
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        with:
          ref: cicd_testing
      - name: building
        run: |
         xcodebuild -workspace PasswordEncryption.xcworkspace -scheme PasswordEncryption -configuration Debug -destination platform="iPhone 11 Pro Simulator"
   #      xcodebuild -workspace PasswordEncryption.xcworkspace -scheme PasswordEncryption clean archive -configuration release -sdk iphoneos -archivePath PasswordEncryption.xcarchive CODE_SIGN_STYLE = Automatic
   #      xcodebuild -exportArchive -archivePath PasswordEncryption.xcarchive -exportOptionsPlist  PasswordEncryption/info.plist -exportPath  PasswordEncryption.ipa
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        working-directory: PasswordEncryption
        run: |
            echo '${{matrix.destiation }}'
            python3 -m pip install Appium-Python-Client
            python3 test_appium.py ${{ matrix.destination }} "${{ matrix.devices }}"

