name: CI-Test

on: [push]

env:
  DAY_OF_WEEK: Monday
  
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          echo "NOW=v$('Sunday' +'%Y%m%d.%H%M%S')" >> $$DAY_OF_WEEK
          echo "$DAY_OF_WEEK!"
