name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['14.5','15.2']
          devices: ['iPhone 12 Pro Simulator','iPhone 11 Pro Simulator']
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
            echo '${{matrix.destiation }}'
            sudo echo "127.0.0.1 splunkRumSmokeTest.local" | sudo tee -a /etc/hosts
            python3 -m pip install Appium-Python-Client
            python3 PasswordEncryption/test_appium.py ${{ matrix.destination }} "${{ matrix.devices }}"

